app = "flyscale"

primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "ghcr.io/spotsnel/flyscale:latest"

[env]
  PORT="41641"
# create a reusable or ephemeral auth key
# ephemeral auth key are not working for use as exit node as they are ipv6 only
# flyctl secrets set TAILSCALE_AUTH_KEY=tskey-...

[experimental]
  auto_rollback = false
  private_network = true

[[services]]
  internal_port = 41641
  protocol = "udp"
  processes = ["app"]

  [[services.ports]]
    port = 41641

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75